### ISSUE TITLE
generate.sh run into error: expected value of type 'NoneType or depset' for parameter 'user_compile_flags'

### ISSUE THREAD

**Issue by zhongweiy** [grailbio/bazel-compilation-database#24]
Hi, there, 
I'm trying to run this tool on [the bazel cpp tutorial project](https://github.com/bazelbuild/examples/).

Here is my command to reproduce the error:
```
$git clone git clone https://github.com/bazelbuild/examples/
$cd examples/cpp-tutorial/stage1
$curl -L https://github.com/grailbio/bazel-compilation-database/archive/0.3.3.tar.gz | tar -xz
$./bazel-compilation-database-0.3.3/generate.sh
ERROR: /playground/bazel_examples/cpp-tutorial/stage1/main/BUILD:1:1: in //bazel-compilation-database-0.3.3:aspects.bzl%compilation_database_aspect aspect on cc_binary rule //main:hello-world: 
Traceback (most recent call last):
	File "/playground/bazel_examples/cpp-tutorial/stage1/main/BUILD", line 1
		//bazel-compilation-database-0.3.3:aspects.bzl%compilation_database_aspect(...)
	File "/playground/bazel_examples/cpp-tutorial/stage1/bazel-compilation-database-0.3.3/aspects.bzl", line 88, in _compilation_database_aspect_impl
		cc_common.create_compile_variables(feature_configuration = feature_..., <2 more arguments>)
expected value of type 'NoneType or depset' for parameter 'user_compile_flags', in method call create_compile_variables(feature_configuration feature_configuration, CcToolchainInfo cc_toolchain, list user_compile_flags) of 'cc_common'
ERROR: Analysis of aspect '//bazel-compilation-database-0.3.3:aspects.bzl%compilation_database_aspect of //main:hello-world' failed; build aborted: Analysis of target '//main:hello-world' failed; build aborted
INFO: Elapsed time: 0.059s
INFO: 0 processes.
```

And my environment is Ubuntu 16.04 and bazel version `0.17.2`.

**Comment by zhongweiy** [comment]
It seems my old version `0.17.2` has some compatible issue. The `user_compile_flags` requires `depset` type in the `0.17.2` version but the passed value is a `list`. It could be solved by:

- upgrade the bazel to latest verion (0.24).
- wrap the `ctx.fragments.cpp.copts` list by `depset` in aspects.bzl
```
 88    compile_variables = cc_common.create_compile_variables(                                                                                                                                                                                                                  
 89        feature_configuration = feature_configuration,                                                                                                                                                                                                                       
 90        cc_toolchain = cc_toolchain,                                                                                                                                                                                                                                         
 91        user_compile_flags = depset(ctx.fragments.cpp.copts),                                                                                                                                                                                                                
 92    )
```

**Comment by siddharthab** [comment]
Thanks! I suspected as much. I do not make this project backward compatible with older versions of bazel, and I am not tracking the minimum supported bazel version. Thank you for your patience.

**Comment by zhongweiy** [comment]
My pleasure:) And thanks for your project!

And one more question is why Bazel don't have the compilation database generation feature officially?
