### ISSUE TITLE
Failed to run the tool on a simple cpp project

### ISSUE THREAD

**Issue by xulongwu4** [grailbio/bazel-compilation-database#27]
Hello,

I tried to use the tool with the cpp project mentioned in the [bazel tutorial](https://docs.bazel.build/versions/master/tutorial/cpp.html#use-multiple-packages) and it failed with the following message
```
INFO: Invocation ID: e383cd09-26d2-4f29-a09c-2a025121ffcb
INFO: Invocation ID: ea115bd3-8d8e-4bf6-a049-ab4c5d2564df
INFO: Invocation ID: 56255735-0db9-4d7d-ad84-ae359abaae09
INFO: Invocation ID: 49f62f16-e595-4ac4-a179-567aaccd3f75
ERROR: /home/oulongwu/tmp/bazel/examples/cpp-tutorial/stage3/main/BUILD:1:1: in //bazel-compilation-database-0.3.4:aspects.bzl%compilation_database_aspect aspect on cc_library rule //main:hello-greet: 
Traceback (most recent call last):
	File "/home/oulongwu/tmp/bazel/examples/cpp-tutorial/stage3/main/BUILD", line 1
		//bazel-compilation-database-0.3.4:aspects.bzl%compilation_database_aspect(...)
	File "/home/oulongwu/tmp/bazel/examples/cpp-tutorial/stage3/bazel-compilation-database-0.3.4/aspects.bzl", line 153, in _compilation_database_aspect_impl
		get_compile_flags(target)
	File "/home/oulongwu/tmp/bazel/examples/cpp-tutorial/stage3/bazel-compilation-database-0.3.4/aspects.bzl", line 78, in get_compile_flags
		compilation_context.includes
object of type 'CompilationContext' has no field 'includes'
ERROR: Analysis of aspect '//bazel-compilation-database-0.3.4:aspects.bzl%compilation_database_aspect of //main:hello-greet' failed; build aborted: Analysis of target '//main:hello-greet' failed; build aborted
INFO: Elapsed time: 0.751s
INFO: 0 processes.
```

I am using bazel version 0.21.0 on linux. Can you suggest how to fix the problem?

**Comment by siddharthab** [comment]
Sorry, I missed seeing this issue.

We no longer support bazel 0.21 at the HEAD of our master branch. bazel is currently not v1, and so undergoes many backward incompatible changes. We currently do not maintain bazel version support branches, but you can use an older release of the project. I think release 0.3.3 will work for your bazel version.
