### ISSUE TITLE
generate.py not working on protocolbuffers/protobuf

### ISSUE THREAD

**Issue by devjgm** [grailbio/bazel-compilation-database#91]
I used to use this to generate the compile_commands.json file, and it used to work when I used `generate.sh`. Now that I'm using `generate.py`, it now gives errors. Here's an easy repro case:

```console
$ git clone --depth 1 https://github.com/grailbio/bazel-compilation-database
Cloning into 'bazel-compilation-database'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 35 (delta 10), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (35/35), 23.48 KiB | 23.48 MiB/s, done.
Resolving deltas: 100% (10/10), done.
$ git clone --depth 1 https://github.com/protocolbuffers/protobuf
Cloning into 'protobuf'...
remote: Enumerating objects: 2731, done.
remote: Counting objects: 100% (2731/2731), done.
remote: Compressing objects: 100% (2143/2143), done.
remote: Total 2731 (delta 1070), reused 1042 (delta 452), pack-reused 0
Receiving objects: 100% (2731/2731), 5.65 MiB | 6.46 MiB/s, done.
Resolving deltas: 100% (1070/1070), done.
$ cd protobuf/
$ ../bazel-compilation-database/generate.py
Starting local Bazel server and connecting to it...
WARNING: /home/jgm/foo/protobuf/BUILD:371:11: target '//:cc_wkt_protos' is deprecated: Only for backward compatibility. Do not use.
ERROR: /home/jgm/.cache/bazel/_bazel_jgm/d9881f88bbd6ba800e422c40c74a4fb9/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: /home/jgm/.cache/bazel/_bazel_jgm/d9881f88bbd6ba800e422c40c74a4fb9/external/local_config_cc/BUILD:47:19: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:3:13: in <toplevel>
Repository rule http_archive defined at:
  /home/jgm/.cache/bazel/_bazel_jgm/d9881f88bbd6ba800e422c40c74a4fb9/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
INFO: Repository 'remote_coverage_tools' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cd14f1cb4559e4723e63b7e7b06d09fcc3bd7ba58d03f354cdff1439bd936a7d' for https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip
If the definition of 'remote_coverage_tools' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//objectivec:objectivec' failed; build aborted:
INFO: Elapsed time: 1.411s
INFO: 0 processes.
Traceback (most recent call last):
  File "/home/jgm/foo/protobuf/../bazel-compilation-database/generate.py", line 106, in <module>
    subprocess.check_call(build_cmd, stdout=subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--override_repository=bazel_compdb=/home/jgm/foo/bazel-compilation-database', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--noshow_progress', '--noshow_loading_progress', '--output_groups=compdb_files,header_files', '--target_pattern_file=/tmp/tmpi2ns1r4f']' returned non-zero exit status 1.
$
```

**Comment by siddharthab** [comment]
It looks like there is a problem with your setup:
```
ERROR: /home/jgm/.cache/bazel/_bazel_jgm/d9881f88bbd6ba800e422c40c74a4fb9/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
```

Do your bazel targets build successfully?

**Comment by devjgm** [comment]
Some do. A `bazel build ...` probably doesn't work on every platform, but some targets do. For example, in the protobuf repo (shown above), `bazel build :protobuf` should work.

In order to generate a compile_commands.json, does a full `...` build need to work? Would it be possible to specify a set of targets for it to use instead of `...`?

**Comment by siddharthab** [comment]
The problem here is that bazel still needs to find the appropriate compilers on your system for all the targets in `...`. More specifically, while it does not need the build phase, it still needs to finish the analysis phase.

I think what is happening in this case, is that it is not able to find the targets to compile the objective-c targets. There has been no change in this behavior within this project, but maybe something changed within bazel.

You can workaround by giving a different query expression than the default using the `-q` [flag](https://github.com/grailbio/bazel-compilation-database/blob/be2ea876e64d9047ead799281f594d7b924c1c09/generate.py#L59).

For example, `../bazel-compilation-database/generate.py -q '//:protoc'` will work.

I am going to close the issue now, but please feel free to reopen.
